---
# Common App Queues
# GitLab + Others like CI
- name: Circle Automation User
  run_once: true
  include_tasks: runners/mkuser.yml
  vars:
    username: circleautomation
  tags:
    - ci

- name: Circle Automation Queue
  run_once: true
  include_tasks: runners/mkqueue.yml
  vars:
    username: circleautomation
    queue_name: circleautomation-ci
    # 10 Days
    message_ttl: 864000000
    routing_keys:
      - "org.cclinux.{{ rabbitmq_env }}.gitlab.#"
      # Testing only
      - "org.cclinux.ci.#"
  tags:
    - ci

- name: OSCI
  run_once: true
  include_tasks: runners/mkqueue.yml
  vars:
    username: "osci-pipeline-{{ rabbitmq_env }}"
    queue_name: "{{ item }}"
    message_ttl: 432000000
    routing_keys:
      - "org.cclinux.ci.#"
  loop:
    - osci-pipeline-queue-0
    - osci-pipeline-queue-1
    - osci-pipeline-queue-2
    - osci-pipeline-queue-3
    - osci-pipeline-queue-4
    - osci-pipeline-queue-5
  tags:
    - osci
# End GitLab and CI

# Koji User
- name: Circle Koji User
  run_once: true
  include_tasks: runners/mkuser.yml
  vars:
    username: circlekoji
# End Koji

# Potential ODCS
- name: Create the circle-odcs vhost
  run_once: true
  delegate_to: "{{ rabbitmq_cluster_list[0] }}"
  community.rabbitmq.rabbitmq_vhost:
    name: circle-odcs
    state: present
  tags:
    - odcs

- name: Configure the odcs HA Policy
  run_once: true
  delegate_to: "{{ rabbitmq_cluster_list[0] }}"
  community.rabbitmq.rabbitmq_policy:
    name: HA
    apply_to: queues
    pattern: ".*"
    tags:
      ha-mode: all
      ha-sync-mode: automatic
      ha-sync-batch-size: 10000
    vhost: circle-odcs
  tags:
    - odcs

- name: Add a policy to keep the odcs vhost swept
  run_once: true
  delegate_to: "{{ rabbitmq_cluster_list[0] }}"
  community.rabbitmq.rabbitmq_policy:
    name: pubsub_sweeper
    apply_to: queues
    state: present
    pattern: ".*"
    tags:
      expires: 111600000
      max-length-bytes: 1073741824
    vhost: circle-odcs
  tags:
    - odcs

# To consider: Separate ODCS Admin Account?
- name: Grant the circleadmin user access to the circle-odcs vhost
  run_once: true
  delegate_to: "{{ rabbitmq_cluster_list[0] }}"
  community.rabbitmq.rabbitmq_user:
    user: circleadmin
    vhost: circle-odcs
    configure_priv: ".*"
    read_priv: ".*"
    write_priv: ".*"
    tags: administrator
  tags:
    - odcs
# ODCS End
